BookStore/Models/Publisher.cs
namespace BookStore.Models
{
    public class Publisher : BaseModel
    {
        public string Location { get; set; } = null!;
        public ICollection<Book> Books { get; set; } = null!;
    }
}

BookStore/Controllers/PublisherController.cs
using BookStore.VM.PublisherVMs;
using FluentValidation.Results;

namespace BookStore.Controllers
{
	public class PublisherController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IImageMethods _ImageMethods;
		private readonly IMapper _mapper;
		private readonly IValidator<CreatePublisherVM> _createPublisherValidator;
		private readonly IValidator<UpdatePublisherVM> _updatePublisherValidator;
		public PublisherController(IUnitOfWork unitOfWork, IImageMethods ImageMethods, IMapper mapper, IValidator<CreatePublisherVM> createPublisherValidator, IValidator<UpdatePublisherVM> updatePublisherValidator)
		{
			_unitOfWork = unitOfWork;
			_ImageMethods = ImageMethods;
			_ImageMethods.SetImagePath(FileSettings.PublishersImagesPath);
			_mapper = mapper;
			_createPublisherValidator = createPublisherValidator;
			_updatePublisherValidator = updatePublisherValidator;
		}
		public async Task<IActionResult?> Index()
		{
			IEnumerable<Publisher> publishers = await _unitOfWork.Publishers.GetAllAsync();

			List<PublisherVM> publisherVm = [];

			foreach (var publisher in publishers.ToList())
			{
				publisherVm.Add(_mapper.Map<PublisherVM>(publisher));
			}

			return View(publisherVm);
		}
		public IActionResult Add()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Add(CreatePublisherVM vm)
		{
			//Validate Vm
			var modelResult = _createPublisherValidator.Validate(vm);
			if (AddErrorToModelResult(modelResult) || await NameValidate(vm.Id, vm.Name)) return View(vm);

			string imageName = await _ImageMethods.SaveImage(vm.Image);
			try
			{
				var publisher = _mapper.Map<Publisher>(vm);
				publisher.ImagePath = imageName;
				await _unitOfWork.Publishers.AddAsync(publisher);
				await _unitOfWork.Publishers.Save();
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				AddErrorToModelResult(modelResult);
				_ImageMethods.DeleteImage(imageName);
				return View(vm);
			}
		}
		public async Task<IActionResult> Update(int id)
		{
			var UpdatePublisherVm = await UpdatePublisher(id);
			if (UpdatePublisherVm is null) return NotFound();
			return View(UpdatePublisherVm);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Update(UpdatePublisherVM vm)
		{
			var modelResult = _updatePublisherValidator.Validate(vm);

			if (AddErrorToModelResult(modelResult) || await NameValidate(vm.Id, vm.Name))
			{
				var UpdatePublisherVm = await UpdatePublisher(vm.Id);
				if (UpdatePublisherVm is null) return NotFound();
				return View(UpdatePublisherVm);
			}

			Publisher? publisher = await _unitOfWork.Publishers.FindAsync(x => x.Id == vm.Id);
			if (publisher == null) BadRequest(ModelState);

			bool hasNewImage = vm.Image is not null;
			string? oldImagePath = publisher?.ImagePath;
			DateTime createdOn = publisher?.CreatedOn ?? DateTime.MinValue;

			publisher = _mapper.Map<Publisher>(vm);
			publisher.CreatedOn = createdOn;

			if (hasNewImage)
			{
				publisher.ImagePath = await _ImageMethods.SaveImage(vm.Image!);
			}
			else
			{
				publisher.ImagePath = oldImagePath;
			}

			_unitOfWork.Publishers.Update(publisher);
			int effectedRows = await _unitOfWork.Publishers.Save();

			if (effectedRows > 0)
			{
				if (hasNewImage) _ImageMethods.DeleteImage(oldImagePath!);
				return RedirectToAction(nameof(Index));
			}

			_ImageMethods.DeleteImage(publisher.ImagePath);
			return BadRequest(ModelState);
		}
		[HttpDelete]
		public async Task<IActionResult> Delete(int id)
		{
			Publisher? publisher = await _unitOfWork.Publishers.GetByIdAsync(id);
			if (publisher is null) NotFound();
			_unitOfWork.Publishers.Delete(publisher);
			int effectedRows = await _unitOfWork.Publishers.Save();
			if (effectedRows > 0) _ImageMethods.DeleteImage(publisher.ImagePath);

			return Ok();
		}
		public async Task<IActionResult?> Details(int id)
		{
			Publisher? publisher = await _unitOfWork.Publishers.GetByIdAsync(id);
			if (publisher is null) return RedirectToAction(nameof(NotFound));
			PublisherVM publisherVM = _mapper.Map<PublisherVM>(publisher);
			return View(publisherVM);
		}
		private bool AddErrorToModelResult(ValidationResult modelResult)
		{
			if (!modelResult.IsValid)
			{
				foreach (var error in modelResult.Errors)
				{
					ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
				}
				return true;
			}
			return !modelResult.IsValid;
		}
		private async Task<bool> NameValidate(int id, string name)
		{
			bool isExist = await _unitOfWork.Publishers.CheckName(name);
			if (!isExist) return isExist;
			Publisher? publisher = await _unitOfWork.Publishers.FindAsync(x => x.Name == name);
			if (isExist && publisher?.Id != id)
			{
				ModelState.AddModelError("Name", "The Publisher Already Exist");
				return true;
			}
			return !isExist;
		}
		private async Task<UpdatePublisherVM> UpdatePublisher(int id)
		{
			var publishers = await _unitOfWork.Publishers.GetByIdAsync(id);
			var UpdatePublisherVm = _mapper.Map<UpdatePublisherVM>(publishers);

			return UpdatePublisherVm;
		}
	}
}

BookStore/Views/Publisher/Add.cshtml
@model CreatePublisherVM
@{
	ViewData["Title"] = "Add New publisher";
}
@section Header {
    Publishers
}

<h2 class="text-center my-5">Add New Publisher</h2>

<section>
	<form asp-controller="Publisher" asp-action="Add" method="post" enctype="multipart/form-data">
		<div class="row">
			<div class="col-12 col-md-6">
				<div class="">
					<label asp-for="Name" class="form-label mt-4">Publisher Title</label>
					<input asp-for="Name" type="text" class="form-control" placeholder="Enter Publisher Name">
					<small class="form-text text-muted"><span asp-validation-for="Name" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Location" class="form-label mt-4">Publisher Location</label>
					<input asp-for="Location" type="text" class="form-control" placeholder="Enter Publisher Location">
					<small class="form-text text-muted"><span asp-validation-for="Location" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Description" class="form-label mt-4">Description</label>
					<textarea asp-for="Description" class="form-control" rows="3"></textarea>
					<small class="form-text text-muted"><span asp-validation-for="Description" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Image" class="form-label mt-4">Choose Cover</label>
					<input asp-for="Image"
						   type="file" class="form-control"
						   data-rule-extension="@FileSettings.ImagesAllowedExtension.Replace(".", string.Empty)"
						   data-msg-extension="Not Allowed Extension"
						   data-rule-maxsize="@FileSettings.ImagesMaxSizeInBytes"
						   data-msg-maxsize="File Is Too Big, Choose File With Size Less Than @{
							@FileSettings.ImagesMaxSizeInMB
}MB">
					<small class="form-text text-muted d-block"><span asp-validation-for="Image" class="text-danger"></span></small>
				</div>

			</div>

			<div class="col-12 col-md-6">
				<img src="#" alt="Cover Preview" id="ImagePreview" class="w-100 object-fit-cover d-none" />
			</div>

		</div>

		<div class="mt-5">
			<button class="btn btn-primary" type="submit">Add</button>
		</div>

	</form>
</section>

@section Scripts {
	<partial name="_ValidationScriptsPartial"></partial>
	<script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
	<script src="~/js/Image.js"></script>
}

BookStore/Views/Publisher/Details.cshtml
@model PublisherVM

@{
	ViewData["Title"] = $"{Model.Name}";
}
@section Header {
    Authors
}
<div class="mb-5 d-sm-flex justify-content-between align-items-center">
	<h1>@Model.Name</h1>
	<div class="mt-sm-0 mt-3">
		<span>@Model.Name  Has Published : <strong>@Model.NumberOfBooks</strong> Books</span>
	</div>
</div>


<div class="row">
	<p class="col-12 col-md-5">@Model.Description</p>
	<div class="col-12 col-md-6 offset-md-1">
		<img src="@($"{FileSettings.PublishersImagesPath}{Model.ImagePath}")" alt="@Model.Name Image" class="img-fluid" />
	</div>
</div>

BookStore/Views/Publisher/Index.cshtml
@model List<PublisherVM>

@{
    ViewData["Title"] = "Publishers";
    var numberOfEntities = 1;
}
@section Header {
    Publishers
}

<section class="w-100 mx-2">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Publishers List</h1>
        <div>
            <a class="btn btn-primary d-flex" asp-controller="Publisher" asp-action="Add"><span>Add New Publisher</span> <span class="ms-2 fs-5"><i class="bi bi-plus"></i></span></a>
        </div>
    </div>

    @if (Model.Count() < 1)
    {
        <div class="alert alert-dismissible alert-info">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <div class="d-inline-block  d-flex align-items-center">
                <i class="bi bi-exclamation-triangle"></i>
                <div class="ms-3">Sorry, No Publishers Has Been Found</div>
            </div>
        </div>
    }
    else
    {
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Publisher Name</th>
                    <th scope="col">Number Of Books</th>
                    <th scope="col">location</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var author in Model)
                {
                    <tr id="row-@author.Id">
                        <th scope="row">@numberOfEntities</th>
                        <td>@author.Name</td>
                        <td>@author.NumberOfBooks</td>
                        <td>@author.Location</td>
                        <td class="d-flex justify-content-center align-items-center">
                            <a asp-action="Update" asp-route-id="@author.Id" class="btn text-primary" title="Edit"><i class="bi bi-pencil-square"></i></a>
                            <a asp-action="Details" asp-route-id="@author.Id" class="btn text-info" title="Details"><i class="bi bi-three-dots-vertical"></i></a>
                            <a href="#" id="@author.Id" class="btn text-danger deleteBtn" title="Delete"><i class="bi bi-trash3-fill"></i></a>
                        </td>
                    </tr>
                    numberOfEntities++;
                }
            </tbody>
        </table>
    }
</section>

@section Styles {
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
}
@section Scripts {
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/js/Component/CloseAlert.js" asp-append-version="true"></script>
    <script src="~/js/DeleteImgScripts/DeleteImage.js" asp-append-version="true" type="module"></script>
    <script src="~/js/DeleteImgScripts/DeletePublisher.js" asp-append-version="true" type="module"></script>
}

BookStore/Views/Publisher/Update.cshtml
@model UpdatePublisherVM
@{
	ViewData["Title"] = "Update Publisher";
}
@section Header {
    Publisher
}

<h2 class="text-center my-5">Update Publisher @Model.Name</h2>

<section>
	<form asp-controller="Publisher" asp-action="Update" method="post" enctype="multipart/form-data">
		<div class="row">
			<div class="col-12 col-md-6">
				<div class="">
					<label asp-for="Name" class="form-label mt-4">Publisher Title</label>
					<input asp-for="Name" type="text" class="form-control" placeholder="Enter Publisher Name">
					<small class="form-text text-muted"><span asp-validation-for="Name" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Location" class="form-label mt-4">Publisher Location</label>
					<input asp-for="Location" type="text" class="form-control" placeholder="Enter Publisher Location">
					<small class="form-text text-muted"><span asp-validation-for="Location" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Description" class="form-label mt-4">Description</label>
					<textarea asp-for="Description" class="form-control" rows="3"></textarea>
					<small class="form-text text-muted"><span asp-validation-for="Description" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Image" class="form-label mt-4">Choose Cover</label>
					<input asp-for="Image"
						   type="file" class="form-control"
						   data-rule-extension="@FileSettings.ImagesAllowedExtension.Replace(".", string.Empty)"
						   data-msg-extension="Not Allowed Extension"
						   data-rule-maxsize="@FileSettings.ImagesMaxSizeInBytes"
						   data-msg-maxsize="File Is Too Big, Choose File With Size Less Than @{
								@FileSettings.ImagesMaxSizeInMB
}MB">
					<small class="form-text text-muted d-block"><span asp-validation-for="Image" class="text-danger"></span></small>
				</div>

			</div>

			<div class="col-12 col-md-6">
				<img src="@($"{FileSettings.PublishersImagesPath}{Model.ImagePath}")" alt="Cover Preview" id="ImagePreview" class="w-100 object-fit-cover" />
			</div>

		</div>

		<div class="mt-5">
			<button class="btn btn-primary" type="submit">Update</button>
		</div>

	</form>
</section>

@section Scripts {
	<partial name="_ValidationScriptsPartial"></partial>
	<script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
	<script src="~/js/Image.js"></script>
}