BookStore/Models/Author.cs
namespace BookStore.Models
{
    public class Author : BaseModel
    {
        public ICollection<BookAuthor> Books { get; set; } = null!;
    }
}

BookStore/Controllers/AuthorController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
	public class AuthorController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IImageMethods _ImageMethods;
		private readonly IMapper _mapper;
		private readonly IValidator<CreateAuthorVM> _createAuthorValidator;
		private readonly IValidator<UpdateAuthorVM> _updateAuthorValidator;
		public AuthorController(IUnitOfWork unitOfWork, IImageMethods ImageMethods, IMapper mapper, IValidator<CreateAuthorVM> createAuthorValidator, IValidator<UpdateAuthorVM> updateAuthorValidator)
        {
            _unitOfWork = unitOfWork;
			_unitOfWork = unitOfWork;
			_ImageMethods = ImageMethods;
			_ImageMethods.SetImagePath(FileSettings.AuthorsImagesPath);
			_mapper = mapper;
            _createAuthorValidator = createAuthorValidator;
            _updateAuthorValidator = updateAuthorValidator;
		}
        public async Task<ActionResult> Index()
		{
			IEnumerable<Author> authors = await  _unitOfWork.Authors.GetAllAsync();
			List<AuthorVM> authorsVM = [];
            foreach (var author in authors.ToList())
            {
				authorsVM.Add(_mapper.Map<AuthorVM>(author));
            }
            return View(authorsVM);
		}
		public IActionResult Add()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Add(CreateAuthorVM vm)
		{
            //Validate Vm
            var modelResult = _createAuthorValidator.Validate(vm);

            if (AddErrorToModelResult(modelResult)) return View(vm);

            string imageName = await _ImageMethods.SaveImage(vm.Image);
			try
			{
                var author = _mapper.Map<Author>(vm);
                author.ImagePath = imageName;
                await _unitOfWork.Authors.AddAsync(author);
                await _unitOfWork.Authors.Save();
                return RedirectToAction(nameof(Index));
            }
			catch
			{
				_ImageMethods.DeleteImage(imageName);
				AddErrorToModelResult(modelResult);
                return View(vm);
			}

		}
		public async Task<IActionResult> Details(int id)
		{
			Author? author = await _unitOfWork.Authors.GetByIdAsync(id);
			if (author is null)
			{
				return RedirectToAction(nameof(NotFound));
			}
			AuthorVM authorVM = _mapper.Map<AuthorVM>(author);
			return View(authorVM);
		}
		public async Task<IActionResult> Update(int id)
		{
			var author = await _unitOfWork.Authors.GetByIdAsync(id);
			if (author is null) return NotFound();
			var UpdateAuthorVm = _mapper.Map<UpdateAuthorVM>(author);
			return View(UpdateAuthorVm);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Update(UpdateAuthorVM vm)
		{
			var modelResult = _updateAuthorValidator.Validate(vm);
			if (AddErrorToModelResult(modelResult)) return View(vm);

			Author? author = await _unitOfWork.Authors.FindAsync(x => x.Id == vm.Id);
			if (author == null) BadRequest(ModelState);

			bool hasNewImage = vm.Image is not null;
			string? oldImagePath = author?.ImagePath;
			DateTime createdOn = author?.CreatedOn ?? DateTime.MinValue;

			author = _mapper.Map<Author>(vm);
			author.CreatedOn = createdOn;

			if (hasNewImage)
			{
				author.ImagePath = await _ImageMethods.SaveImage(vm.Image!);
			}
			else
			{
				author.ImagePath = oldImagePath;
			}

			_unitOfWork.Authors.Update(author);
			int effectedRows = await _unitOfWork.Categories.Save();

			if (effectedRows > 0)
			{
				if (hasNewImage) _ImageMethods.DeleteImage(oldImagePath!);
				return RedirectToAction(nameof(Index));
			}

			_ImageMethods.DeleteImage(author.ImagePath);
			return BadRequest(ModelState);
		}
		[HttpDelete]
		public async Task<IActionResult> Delete(int id)
		{
			Author? author = await _unitOfWork.Authors.GetByIdAsync(id);
			if (author is null) NotFound();
			_unitOfWork.Authors.Delete(author);
			int effectedRows = await _unitOfWork.Authors.Save();
			if (effectedRows > 0) _ImageMethods.DeleteImage(author.ImagePath);

			return Ok();
		}
        private bool AddErrorToModelResult(ValidationResult modelResult)
        {
			if (!modelResult.IsValid)
			{
				foreach (var error in modelResult.Errors)
				{
					ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
				}
				return true;
			}
			return !modelResult.IsValid;
		}
    }
}

BookStore/Views/Author/Add.cshtml
@model CreateAuthorVM
@{
	ViewData["Title"] = "Add New author";
}
@section Header {
    Authors
}

<h2 class="text-center my-5">Add New Author</h2>

<section>
	<form asp-controller="Author" asp-action="Add" method="post" enctype="multipart/form-data">
		<div class="row">
			<div class="col-12 col-md-6">
				<div class="">
					<label asp-for="Name" class="form-label mt-4">Author Title</label>
					<input asp-for="Name" type="text" class="form-control" placeholder="Enter Author Name">
					<small class="form-text text-muted"><span asp-validation-for="Name" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Description" class="form-label mt-4">About</label>
					<textarea asp-for="Description" class="form-control" rows="3"></textarea>
					<small class="form-text text-muted"><span asp-validation-for="Description" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Image" class="form-label mt-4">Choose Cover</label>
					<input asp-for="Image"
						   type="file" class="form-control"
						   data-rule-extension="@FileSettings.ImagesAllowedExtension.Replace(".", string.Empty)"
						   data-msg-extension="Not Allowed Extension"
						   data-rule-maxsize="@FileSettings.ImagesMaxSizeInBytes"
						   data-msg-maxsize="File Is Too Big, Choose File With Size Less Than @{
						@FileSettings.ImagesMaxSizeInMB
}MB">
					<small class="form-text text-muted d-block"><span asp-validation-for="Image" class="text-danger"></span></small>
				</div>

			</div>

			<div class="col-12 col-md-6">
				<img src="#" alt="Cover Preview" id="ImagePreview" class="w-100 object-fit-cover d-none" />
			</div>

		</div>

		<div class="mt-5">
			<button class="btn btn-primary" type="submit">Add</button>
		</div>

	</form>
</section>

@section Scripts {
	<partial name="_ValidationScriptsPartial"></partial>
	<script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
	<script src="~/js/Image.js"></script>
}

BookStore/Views/Author/Details.cshtml
@model AuthorVM

@{
	ViewData["Title"] = $"";
}
@section Header {
    Authors
}
<div class="mb-5 d-sm-flex justify-content-between align-items-center">
	<h1>@Model.Name</h1>
	<div class="mt-sm-0 mt-3">
		<span>@Model.Name  Has : <strong>@Model.NumberOfBooks</strong> Books</span>
	</div>
</div>


<div class="row">
	<p class="col-12 col-md-5">@Model.Description</p>
	<div class="col-12 col-md-6 offset-md-1">
		<img src="@($"{FileSettings.AuthorsImagesPath}{Model.ImagePath}")" alt="@Model.Name Image" class="img-fluid" />
	</div>
</div>

BookStore/Views/Author/Index.cshtml
@model List<AuthorVM>

@{
    ViewData["Title"] = "Authors";
    var numberOfEntities = 1;
}
@section Header {
    Authors
}

<section class="w-100 mx-2">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Books List</h1>
        <div>
            <a class="btn btn-primary d-flex" asp-controller="Author" asp-action="Add"><span>Add New Author</span> <span class="ms-2 fs-5"><i class="bi bi-plus"></i></span></a>
        </div>
    </div>

    @if (Model.Count() < 1)
    {
        <div class="alert alert-dismissible alert-info">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <div class="d-inline-block  d-flex align-items-center">
                <i class="bi bi-exclamation-triangle"></i>
                <div class="ms-3">Sorry, No Authors Has Been Found</div>
            </div>
        </div>
    }
    else
    {
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Author Name</th>
                    <th scope="col">Number Of Books</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var author in Model)
                {
                    <tr id="row-@author.Id">
                        <th scope="row">@numberOfEntities</th>
                        <td>@author.Name</td>
                        <td>@author.NumberOfBooks</td>
                        <td class="d-flex justify-content-center align-items-center">
                            <a asp-action="Update" asp-route-id="@author.Id" class="btn text-primary" title="Edit"><i class="bi bi-pencil-square"></i></a>
                            <a asp-action="Details" asp-route-id="@author.Id" class="btn text-info" title="Details"><i class="bi bi-three-dots-vertical"></i></a>
                            <a href="#" id="@author.Id" class="btn text-danger deleteBtn" title="Delete"><i class="bi bi-trash3-fill"></i></a>
                        </td>
                    </tr>
                    numberOfEntities++;
                }
            </tbody>
        </table>
    }
</section>

@section Styles {
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
}
@section Scripts {
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/js/Component/CloseAlert.js" asp-append-version="true"></script>
    <script src="~/js/DeleteImgScripts/DeleteImage.js" asp-append-version="true" type="module"></script>
    <script src="~/js/DeleteImgScripts/DeleteAuthor.js" asp-append-version="true" type="module"></script>
}

BookStore/Views/Author/Update.cshtml
@model UpdateAuthorVM
@{
	ViewData["Title"] = "Update Author";
}
@section Header {
    Author
}

<h2 class="text-center my-5">Update Author @Model.Name</h2>

<section>
	<form asp-controller="Author" asp-action="Update" method="post" enctype="multipart/form-data">
		<div class="row">
			<div class="col-12 col-md-6">
				<div class="">
					<label asp-for="Name" class="form-label mt-4">Author Title</label>
					<input asp-for="Name" type="text" class="form-control" placeholder="Enter Author Name">
					<small class="form-text text-muted"><span asp-validation-for="Name" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Description" class="form-label mt-4">About</label>
					<textarea asp-for="Description" class="form-control" rows="3"></textarea>
					<small class="form-text text-muted"><span asp-validation-for="Description" class="text-danger"></span></small>
				</div>

				<div class="">
					<label asp-for="Image" class="form-label mt-4">Choose Cover</label>
					<input asp-for="Image"
						   type="file" class="form-control"
						   data-rule-extension="@FileSettings.ImagesAllowedExtension.Replace(".", string.Empty)"
						   data-msg-extension="Not Allowed Extension"
						   data-rule-maxsize="@FileSettings.ImagesMaxSizeInBytes"
						   data-msg-maxsize="File Is Too Big, Choose File With Size Less Than @{
							@FileSettings.ImagesMaxSizeInMB
}MB">
					<small class="form-text text-muted d-block"><span asp-validation-for="Image" class="text-danger"></span></small>
				</div>

			</div>

			<div class="col-12 col-md-6">
				<img src="@($"{FileSettings.AuthorsImagesPath}{Model.ImagePath}")" alt="Cover Preview" id="ImagePreview" class="w-100 object-fit-cover" />
			</div>

		</div>

		<div class="mt-5">
			<button class="btn btn-primary" type="submit">Update</button>
		</div>

	</form>
</section>

@section Scripts {
	<partial name="_ValidationScriptsPartial"></partial>
	<script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
	<script src="~/js/Image.js"></script>
}